### ISSUE TITLE
Implement differentiable coverage probability regularizer

### ISSUE THREAD

**Issue by macio232** [probabilists/lampe#14]
### Description

The method described in [Calibrating Neural Simulation-Based Inference with Differentiable Coverage Probability](https://arxiv.org/abs/2310.13402) paper.

### Implementation

New loss class in the `inference` module, similar to the [NRELoss](https://lampe.readthedocs.io/en/stable/api/lampe.inference.html#lampe.inference.NRELoss) ->[BNRELoss](https://lampe.readthedocs.io/en/stable/api/lampe.inference.html#lampe.inference.BNRELoss) enhancement.

Two separate classes, one for NRE, and one for NPE.

### Alternatives

I did not consider alternatives.

**Comment by francois-rozet** [comment]
Hello @macio232 thanks for the feature request! I'll take a look at the PR soon!
